[STRAT-95] Solcast and Weatherbit API call script drafts
uw-midsun/strategy pull request #102
Opened 2021-01-16 20:42 UTC by linnall

2021-01-17 02:25 UTC, e-wai reviewed
It's doing what we expect (yay), but left a couple thoughts. Were there any questions you had for me?

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/solcast-api-test.py
> +api_key = 'na'
I'd recommend creating the `config.py` file that way you don't have to worry about accidentally pushing it up; then you just import it as `from config import SOLCAST_API_KEY`

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/solcast-api-test.py
> +#driver code
Try wrapping this in an if statement (`if __name__=="__main__":`), otherwise CI will flag it

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/solcast-api-test.py
> +        return json.loads(response.content.decode('utf-8'))
Nice, what does a sample response look like? and/or Can we add a variable that takes the right value from this response content?

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/weatherbit-api-test.py
> +	h = next(asc2018)
If you don't ever need this variable, I think you can just go `next(asc2018)`

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/weatherbit-api-test.py
> +# will edit this path so it is not reliant on my computer
path fix :))

2021-01-17 02:25 UTC, e-wai commented on routemodel/solar_rad/weatherbit-api-test.py
> +		#wait 15 minutes (900 seconds, assuming we reach every new destination in 15 minutes)
What was the conclusion around making API calls for current time + place _and_ future locations + times?

2021-02-09 02:15 UTC, ufshk commented
Not sure if this is ready? If it's just a draft you can "Convert to draft" right under where you can request reviewers.

Screenshot below. WARNING: badly highlighted.

![image](https://user-images.githubusercontent.com/30248899/107306379-c6329b80-6a52-11eb-884c-0fe3e08eb3b2.png)

2021-03-10 23:16 UTC, e-wai approved these changes

2021-03-10 23:16 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/solcast-api-test.py
> +import json
delete this file

2021-03-10 23:16 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/solcast-prediction-accuracy.py
> +import time
What are the timezones like through route? @e-wai

2021-03-10 23:16 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/utilities.py
> +    return distance/SPEED
newline pls

2021-03-10 23:16 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/solcast-prediction-accuracy.py
> +import utilities #utility functions
`from utilities import _, _, _`

2021-03-10 23:16 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/weatherbit-api-test.py
> +import json
delete file?

2021-03-10 23:17 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/solcast-prediction-accuracy.py
> +with open(path, 'r') as asc2018:
(ie., just through this long block)

2021-03-15 05:58 UTC, e-wai requested changes
some last minute changes... and can you add a comment about the four hour pause you ran into while testing?

2021-03-15 05:58 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/utilities.py
> +    t1 = math.pow(math.sin(diff1/2), 2)
can we throw spaces around multiplication, division signs please

2021-03-15 05:58 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/utilities.py
> +def getTime(distance):
quick style thing can we change from `getTime` to `get_time`

2021-03-24 02:40 UTC, e-wai approved these changes
i'm sorry super nitpicky

2021-03-24 02:40 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/utilities.py
>  def findDistance(a1, a2, b1, b2):
one more!

2021-03-25 23:27 UTC, e-wai approved these changes
Looks good to me

2021-03-27 18:46 UTC, e-wai commented on routemodel/data_retrieval/solar_rad/solcast-response.txt
> +null
What's this for?

2021-03-29 05:06 UTC, e-wai requested changes
I think you might've reset a commit? You've lost some changes from previous iterations/comments. (I could be very wrong, let me know if I'm missing something)

2021-04-17 19:13 UTC, e-wai approved these changes

2021-04-17 19:16 UTC, merged