[STRAT-116] Add messages in README.md for onboarding tutorial
uw-midsun/strategy pull request #103
Opened 2021-01-16 21:15 UTC by e-wai

+ Made into the README.md to demonstrate the git flow for strategy

Better PR:
+ context on ticket 
+ information on "why" we approached the ticket the way we did
+ reviewers, check this change in x file

2021-01-16 21:17 UTC, ufshk requested changes
please remove this line thanks

2021-01-16 21:17 UTC, ufshk commented on README.md
> +: (
Unnecessary and saddening comment

2021-01-16 21:17 UTC, e-wai commented on README.md
> +: (
It's in honour of the term starting

2021-01-23 22:09 UTC, e-wai commented
Just an example

2021-01-23 22:09 UTC, closed without merging