Weather coordinates
uw-midsun/strategy pull request #116
Opened 2021-02-20 22:55 UTC by SallyYang02

Added in the code (line 14-25) for all of the coordinates in the ASC2021 by making a nested list of all coordinates. Was wondering if there is a better way of calling each pair of coordinates (i.e. for loops) rather than manually indexing each and every point's lat and lon. Will add more code soon.

2021-03-03 23:59 UTC, mdshiozaki approved these changes
overall looks good with TODOs in place for the work that's coming. Looks fine to me

2021-03-04 23:11 UTC, e-wai requested changes

2021-03-04 23:11 UTC, e-wai commented on weather_get.py
> +        lon = locations[0][1].strip()
I'm a tad bit confused around what's happening here? Assuming that from the CSV, we want a list like:

`[[lat, lon], [lat, lon], [lat, lon]]`

on which we're going to make API calls for each point?

2021-03-04 23:11 UTC, e-wai commented on weather_get.py
> +        lon = locations[0][1].strip()
In my head, the easiest way to do that is to declare an empty list before line 11, and for each row, use `.append([lat, lon])`

2021-03-05 00:06 UTC, e-wai commented
Also, two quick things: did you mean to commit into the `weather-pairing` branch? Can we change the title of this PR to `[STRAT-#] Description`

2021-03-13 15:26 UTC, SallyYang02 commented on weather_get.py
> +            i = int(i)
My IDE was giving me an error for not specifying i as an integer so I just it there as a precautionary measure. We can definitely remove that line if it works on everyone else's end.

2021-03-27 18:27 UTC, e-wai requested changes

2021-03-27 18:27 UTC, e-wai commented on weather_get.py
> +        for i in range (len(row)):
You can remove lines 16-18, and then move line 19 to below 23

2021-03-27 18:27 UTC, e-wai commented on weather_get.py
> +        print(location)
I would move line 20 below whenever `append` is called

2021-03-27 18:27 UTC, e-wai commented on weather_get.py
> +            location.append([lat,lon])
`location.append([float(lat), float(lon)])`

2021-03-27 18:27 UTC, e-wai commented on weather_get.py
> +        lon = row[0][1].strip()
```suggestion
lat = row[0]
lon = row[1].strip()
```

2021-03-29 05:08 UTC, e-wai approved these changes
Looks good to me! 

I think eventually we should talk about how this will interact with other files (ie. we may need to wrap this in a function that calls it, saving into CSV is a related ticket as well) but we can keep that for future tickets 🎆

2021-04-06 00:55 UTC, merged

2021-04-10 05:31 UTC, e-wai commented
Something weird happened here - I can't find this file in the repo, and it's not listed as having a file path. @ufshk @mdshiozaki am I going crazy?

2021-04-11 17:27 UTC, ufshk commented
> 
> 
> Something weird happened here - I can't find this file in the repo, and it's not listed as having a file path. @ufshk @mdshiozaki am I going crazy?

It wasn't merged into master. That's why you can't find it in the repo.

It also does not have a filepath, it was put into the top-level directory on the branch it was merged into.