STRAT 149 - CSV file for lead times and prices
uw-midsun/strategy pull request #127
Opened 2021-05-14 01:04 UTC by rodrigotiscareno

2021-05-15 18:22 UTC, e-wai requested changes

2021-05-15 18:22 UTC, e-wai commented on displays/parseCSV.py
> +        value = df1.loc[df1['Digi-Key Part Number'] == partNumber, "Mfg Std Lead Time"].values[0]
+ Do we know for sure that there will only be one listing of the part number (ie. unique entry, and the filtering by `[0]` doesn't hide anything)?
+ Is the formatting for the part number consistent across both? (@mdshiozaki - do we have to parse around dashes or anything?)

2021-05-15 18:22 UTC, e-wai commented on displays/parseCSV.py
> +# - The third parameter is either the Digi-Key Part Number or the Mouser Part Number. The part number is to be entered as a string, as with the other CSV names.
Nice to see, but probably not useful anymore?

2021-05-15 18:22 UTC, e-wai commented on displays/parseCSV.py
> +# Testing - Assuming names for the CSV files and selecting random part number from BomSample_.csv
nitpicky, but this comment doesn't tell us much and can probably be deleted?

2021-05-15 18:22 UTC, e-wai commented on displays/parseCSV.py
> +parseCSV('BomSample_.csv','MidnightSun-Jan28-QuoteRequest.csv','490-4789-1-ND')
Just to be careful, can you throw this under a `if __name__=='__main':`

2021-05-21 01:06 UTC, e-wai requested changes
Hey, so an updated list of constraints from Kristen:

+ Both the Mouse and Digikey lists are exhaustive of all the parts we want -> both lists are of equal lengths, and each have a row per item we're interested in. The number is listed under `Manufacturer Part Number` for Digikey and `Mfr. #` for Mouser. _However_, we need to remove dashes in the dashes in order to compare against both.

+ We're not just entering a single partNumber, but rather creating two updated lists ->  a list of all the parts that Digikey wins (according to the last bullet point's logic) and a list of al lthe parts that Mouser wins. Save these as two separate CSV files, please, and include the price and lead time details!

+ For each, the logic we want is that the lesser price wins UNLESS the lead time > 15 weeks (and let's keep 15 weeks as a parameter in case we want to change in the future)

2021-06-22 05:47 UTC, e-wai reviewed
Hey sorry for the delay - has anyone reached out to talk about adding a `priority` field on the inputs? (If not, maybe we can talk on Slack?)

2021-06-22 05:47 UTC, e-wai commented on displays/parseCSV.py
> +            Bom_Winners.append(i)
When is this case reached?

2021-07-25 06:47 UTC, e-wai requested changes
Looks great 🎉 

Couple of last details:
- When I run it, there are a couple dependencies that I'm missing. Can we add `xlrd`, `openpyxl` to the `requirements.txt`? I can also check with Kristen whether all CSVs are used, because that's preferable imo
- Can we create a subdirectory within `utility` to change the file paths -> `utility/hardware_bom`
- Can we rename `parseCSV.py` to something more specific + descriptive, maybe `select_hardware_bom_purchases.py` or `hardware_bom_purchases.py` or `parse_hardware_bom.py`?

2021-07-25 06:47 UTC, e-wai commented on utility/parseCSV.py
> +def parseCSV(Bom, MS_Quote):
See overall comment - rename this too please!

2021-07-25 06:47 UTC, e-wai commented on utility/parseCSV.py
> +def parseCSV(Bom, MS_Quote):
+ also can we rename the variables to bom_file and MS_quote_file? more descriptive

2021-07-25 06:47 UTC, e-wai commented on utility/parseCSV.py
> +    MS_Quote_DF = pd.read_excel(MS_Quote)
Thinking that we should check with Kristen whether we will always get first script in csv, and second in excel. Feels like something we might trip on in future uses

2021-07-25 06:47 UTC, e-wai commented on utility/parseCSV.py
> +    parseCSV('Bom.csv', 'MS Quote Request.xls')
Can we add another line below here to verify something happened? As simple as

```python
    print("Wrote selected purchases to Bom_Parts.xlsx and MS_Quote_Parts.xlsx")
```

2021-07-28 03:50 UTC, closed without merging

2021-07-28 03:51 UTC, rodrigotiscareno commented
Please refer to new PR [STRAT 149] CSV file for lead times and prices.